### ISSUE TITLE
whisper-timestamped 1.15.4 not compliant with openai-whisper 20240930

### ISSUE THREAD

**Issue by dchapelet** [linto-ai/whisper-timestamped#219] opened 2024-10-16 10:35 UTC
Hello,
I updated to the latest openai-whisper version (_20240930_) but now I have an error with whisper-timestamped v1.15.4.
The error returned is a "None type object with Shape" issue
To work around, I had to rollback openai-whipser to 20231117.
Thank you very much for your help

**Comment by Jeronymous** [comment] 2024-10-29 15:20
duplicate of https://github.com/linto-ai/whisper-timestamped/issues/212

**Closed by Jeronymous** 2024-10-29 15:20 UTC
Labels: duplicate
