### ISSUE TITLE
Can we get a speed boost of %80?

### ISSUE THREAD

**Issue by FlowDownTheRiver** [linto-ai/whisper-timestamped#66] opened 2023-03-21 21:30 UTC
I am using whisper timestamped from cli and some code based on your work.So first of all thank you very much. However this just poped up into my eye https://github.com/guillaumekln/faster-whisper , the page is like a tech demo. I tried it and I was only able to run it with cpu,even though I have cuda and cudnn installed.Anyway the models needs to be converted from Huggingface format. This is like asking for a lot but if you have time and figure it out,can we have a faster-whisper-timestamped repo alongside your work on this one? It shall act like this work of yours but it reads the models from other format.

**Comment by FlowDownTheRiver** [comment] 2023-03-21 21:44
This is the model I have cloned from hugging face ![2023-03-22 00_40_41-whisper-tiny en](https://user-images.githubusercontent.com/71787427/226747974-a73675c0-b5d3-48fe-be99-e979fd5a2a51.jpg)
and this is the output model after converting(from their converting script) for faster whisper :
![2023-03-22 00_40_53-whisper-tiny en-ct2](https://user-images.githubusercontent.com/71787427/226748120-c167dbf6-d97a-465f-8a78-b92c6c811985.jpg)

**Comment by darnn** [comment] 2023-03-21 22:23
Frankly, Faster Whisper runs abysmally on my system (and fails to identify the language of my file properly), but that's just using their sample code, since I don't know the first thing about Python, so maybe I'm doing something wrong.
But, since we're on the subject, there's this:
https://github.com/ggerganov/whisper.cpp
On the basis of which, this was created:
https://github.com/Const-me/Whisper
Described as a "Windows port of whisper.cpp utilising vendor-agnostic GPGPU based on DirectCompute", which means little to me except that it works way faster than any other version of Whisper on my computer. So if we're talking pie in the sky here, I'd love to have something like that for this.

**Comment by kamranjon** [comment] 2023-03-22 17:41
This is a duplicate of this issue here: https://github.com/linto-ai/whisper-timestamped/issues/40 - there is good discussion in that thread if you are interested.

**Comment by Jeronymous** [comment] 2023-03-23 13:52
Indeed. Closing as duplicate.

**Closed by Jeronymous** 2023-03-23 13:52 UTC
